security:

    encoders:
        App\DDD\Domain\Entity\User\User:
            algorithm: argon2i
            cost: 12

    providers:

        database_users:
            entity:
                class: App\DDD\Domain\Entity\User\User
                property: email

        db_custom_provider:
            id: App\DDD\Security\User\Provider\UserProvider

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: db_custom_provider
            form_login:
                login_path: security_login
                check_path: security_login
                default_target_path: home
                username_parameter: _email
                password_parameter: _password

    access_control:
        # matches /home
        - { path: ^/home, roles: ROLE_USER }
        # matches /admin/* except for anything matching the above rule
        - { path: ^/admin, roles: ROLE_ADMIN }