# Check all configuration command available : bin/console config:dump-reference security
security:

    encoders:
        App\DDD\Domain\Entity\User\User:
            algorithm: argon2i
            cost: 12

    providers:

        db_custom_provider:
            id: App\DDD\Security\User\Provider\UserProvider
            #entity:
            #    class: App\DDD\Domain\Entity\User\User
            #    property: email

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secutity_firewall:

            pattern: ^/

            guard:
                provider: db_custom_provider
                authenticators:
                - App\DDD\Security\User\Authenticator\LoginFormAuthenticator

            anonymous: ~

            form_login:
                provider:             db_custom_provider
                remember_me:          true
                success_handler:      ~
                failure_handler:      ~
                check_path:           security_login
                use_forward:          false
                require_previous_session: false
                username_parameter:   _email
                password_parameter:   _password
                csrf_parameter:       _csrf_token
                csrf_token_id:        authenticate
                post_only:            true
                always_use_default_target_path: false
                default_target_path:  /home
                login_path:           security_login
                target_path_parameter: _target_path
                use_referer:          false
                failure_path:         null
                failure_forward:      false
                failure_path_parameter: _failure_path
                #csrf_token_generator: ~

            logout:
                path:                 security_logout
                target:               security_login
                success_handler:      ~
                invalidate_session:   true

            remember_me:
                secret:               '%kernel.secret%'
                token_provider:       ~
                user_providers:       []
                catch_exceptions:     true
                name:                 ddd_remember_me
                lifetime:             2592000 # 30 days in seconds
                path:                 /
                domain:               ~

            user_checker: App\DDD\Security\User\Checker\UserChecker

    access_control:
        # matches route /home
        - { path: ^/%locale%/accueil, roles: ROLE_USER }
        - { path: ^/%locale%/homepage, roles: ROLE_USER }
        # matches route /login
        - { path: ^/%locale%/connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%locale%/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # matches route /logout
        - { path: ^/%locale%/logout, roles: IS_AUTHENTICATED_FULLY }
        # matches route /registration
        - { path: ^/%locale%/inscription, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%locale%/registration, roles: IS_AUTHENTICATED_ANONYMOUSLY }
