twig:
    default_path: '%kernel.project_dir%/src/DDD/UserInterface/WEB/Templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']
