<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'console.command.messenger_debug' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/Command/DebugCommand.php';

$this->privates['console.command.messenger_debug'] = $instance = new \Symfony\Component\Messenger\Command\DebugCommand(array('messenger.bus.default' => array('App\\DDD\\Application\\UseCase\\Command\\User\\Registration\\Interfaces\\RegistrationCommandInterface' => array(0 => 'App\\DDD\\Application\\UseCase\\Command\\User\\Registration\\Handler\\RegistrationHandler'), 'App\\DDD\\Application\\UseCase\\Query\\User\\Login\\Interfaces\\LoginQueryInterface' => array(0 => 'App\\DDD\\Application\\UseCase\\Query\\User\\Login\\Handler\\LoginQueryHandler'))));

$instance->setName('debug:messenger');

return $instance;
