<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\DDD\UserInterface\WEB\Action\User\Login\LoginAction' shared autowired service.

include_once $this->targetDirs[3].'/src/DDD/UserInterface/WEB/Action/User/Login/Interfaces/LoginActionInterface.php';
include_once $this->targetDirs[3].'/src/DDD/UserInterface/WEB/Action/User/Login/LoginAction.php';

return $this->services['App\DDD\UserInterface\WEB\Action\User\Login\LoginAction'] = new \App\DDD\UserInterface\WEB\Action\User\Login\LoginAction(($this->services['twig'] ?? $this->getTwigService()), ($this->services['form.factory'] ?? $this->load('getForm_FactoryService.php')), ($this->services['message_bus'] ?? $this->getMessageBusService()), ($this->services['router'] ?? $this->getRouterService()), ($this->services['security.authentication_utils'] ?? $this->load('getSecurity_AuthenticationUtilsService.php')));
