<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'messenger.bus.default.middleware.handle_message' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/messenger/Middleware/MiddlewareInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/Handler/HandlersLocatorInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/Handler/HandlersLocator.php';
include_once $this->targetDirs[3].'/vendor/symfony/dependency-injection/Argument/RewindableGenerator.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/Handler/MessageHandlerInterface.php';
include_once $this->targetDirs[3].'/src/DDD/Application/UseCase/Command/User/Registration/Handler/Interfaces/RegistrationHandlerInterface.php';
include_once $this->targetDirs[3].'/src/DDD/Application/UseCase/Command/User/Registration/Handler/RegistrationHandler.php';
include_once $this->targetDirs[3].'/src/DDD/Application/UseCase/Query/User/Login/Handler/Interfaces/LoginQueryHandlerInterface.php';
include_once $this->targetDirs[3].'/src/DDD/Application/UseCase/Query/User/Login/Handler/LoginQueryHandler.php';
include_once $this->targetDirs[3].'/vendor/symfony/security-core/Encoder/PasswordEncoderInterface.php';
include_once $this->targetDirs[3].'/src/DDD/Domain/Security/Encoder/Interfaces/EncoderInterface.php';
include_once $this->targetDirs[3].'/src/DDD/Domain/Security/Encoder/Encoder.php';

return $this->privates['messenger.bus.default.middleware.handle_message'] = new \Symfony\Component\Messenger\Middleware\HandleMessageMiddleware(new \Symfony\Component\Messenger\Handler\HandlersLocator(array('App\\DDD\\Application\\UseCase\\Command\\User\\Registration\\Interfaces\\RegistrationCommandInterface' => \current(array(0 => array(0 => new \App\DDD\Application\UseCase\Command\User\Registration\Handler\RegistrationHandler(($this->privates['App\DDD\Infrastructure\User\Repository\UserCommandRepository'] ?? $this->load('getUserCommandRepositoryService.php')), ($this->services['security.password_encoder'] ?? $this->load('getSecurity_PasswordEncoderService.php')))))), 'App\\DDD\\Application\\UseCase\\Query\\User\\Login\\Interfaces\\LoginQueryInterface' => \current(array(0 => array(0 => new \App\DDD\Application\UseCase\Query\User\Login\Handler\LoginQueryHandler(($this->privates['App\DDD\Infrastructure\User\Repository\UserQueryRepository'] ?? $this->load('getUserQueryRepositoryService.php')), new \App\DDD\Domain\Security\Encoder\Encoder())))))));
