<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'messenger.transport.amqp' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/messenger/Transport/Receiver/ReceiverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/Transport/Sender/SenderInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/Transport/TransportInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/Transport/TransportFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/Transport/TransportFactory.php';

return $this->privates['messenger.transport.amqp'] = (new \Symfony\Component\Messenger\Transport\TransportFactory(new RewindableGenerator(function () {
    yield 0 => ($this->privates['messenger.transport.amqp.factory'] ?? $this->load('getMessenger_Transport_Amqp_FactoryService.php'));
}, 1)))->createTransport($this->getEnv('MESSENGER_TRANSPORT_DSN'), array());
