<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'messenger.transport.amqp.factory' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/messenger/Transport/TransportFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/Transport/AmqpExt/AmqpTransportFactory.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/Transport/Serialization/SerializerInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/Transport/Serialization/Serializer.php';

return $this->privates['messenger.transport.amqp.factory'] = new \Symfony\Component\Messenger\Transport\AmqpExt\AmqpTransportFactory(new \Symfony\Component\Messenger\Transport\Serialization\Serializer(($this->services['serializer'] ?? $this->load('getSerializerService.php')), 'json', array()), true);
