<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\DDD\Infrastructure\User\Repository\UserCommandRepository' shared autowired service.

include_once $this->targetDirs[3].'/vendor/doctrine/persistence/lib/Doctrine/Common/Persistence/ObjectRepository.php';
include_once $this->targetDirs[3].'/vendor/doctrine/collections/lib/Doctrine/Common/Collections/Selectable.php';
include_once $this->targetDirs[3].'/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php';
include_once $this->targetDirs[3].'/vendor/doctrine/doctrine-bundle/Repository/ServiceEntityRepositoryInterface.php';
include_once $this->targetDirs[3].'/vendor/doctrine/doctrine-bundle/Repository/ServiceEntityRepository.php';
include_once $this->targetDirs[3].'/src/DDD/Domain/Repository/User/Interfaces/UserCommandRepositoryInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/doctrine-bridge/Security/User/UserLoaderInterface.php';
include_once $this->targetDirs[3].'/src/DDD/Infrastructure/User/Repository/UserCommandRepository.php';

return $this->privates['App\DDD\Infrastructure\User\Repository\UserCommandRepository'] = new \App\DDD\Infrastructure\User\Repository\UserCommandRepository(($this->services['doctrine'] ?? $this->getDoctrineService()));
