<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL7zp6vG\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL7zp6vG/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerL7zp6vG.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerL7zp6vG\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerL7zp6vG\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'L7zp6vG',
    'container.build_id' => 'fa43e68b',
    'container.build_time' => 1546895820,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerL7zp6vG');
