<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXMDQXD4\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXMDQXD4/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXMDQXD4.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXMDQXD4\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXMDQXD4\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'XMDQXD4',
    'container.build_id' => 'e4ce98d5',
    'container.build_time' => 1546879620,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXMDQXD4');
